[package]
name = "modelo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
serde_json = "1.0.100"

[dev-dependencies]
gl = "0.14.0"
sdl2 = "0.35.2"
